#ifndef TESTDRIVER_H
#define TESTDRIVER_H

struct mystruct {
    int num;
    char name[64];
};

#define MY_DEVICE 0x8000

#define WR_VALUE  CTL_CODE(MY_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define RD_VALUE  CTL_CODE(MY_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define WR_STRUCT CTL_CODE(MY_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
#define RD_STRUCT CTL_CODE(MY_DEVICE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS)

#endif // TESTDRIVER_H
